### PR TITLE
Final changes for v1.0.6

### LINKED ISSUE #218: Update minimum required version of moz_crlite_query
The moz_crlite_query script has been updated to respect coverage metadata. Once a new version is released we need to bump the minimum required version here.

### LINKED ISSUE #220: Wrong units/scaling for time.Duration lead to liveness probe failures
Our staging instance of ct-fetch is failing liveness probe tests because the maximum time since last update is set too small.

### LINKED ISSUE #222: Avoid duplicate log::url keys in redis
In older versions of ct-fetch it's possible to create a pair of entries in redis with keys `log::example.com` and `log::example.com/`. Newer versions omit the slash. Our production instance of ct-fetch has some keys with the slash. We should migrate these entries on upgrade.

### PR DESCRIPTION
**Pull request by jschanck**
Commit ad65b2a resolves #218. The three commits that follow are minor changes. Commit a2c5f29 resolves #220. Commit 7432053 resolves #222.

### CODE REVIEW

File: go/cmd/ct-fetch/ct-fetch.go [hunk 1]
```diff
@@ -520,12 +531,13 @@ func (ld *LogSyncEngine) NewLogWorker(ctx context.Context, ctLogData *types.CTLo
 
 func (lw *LogWorker) sleep(ctx context.Context) {
 	// Sleep for ctconfig.PollingDelay seconds (+/- 10%).
-	duration := time.Duration((1 + 0.1*rand.NormFloat64()) * float64(*ctconfig.PollingDelay))
```
Comment (mozkeeler) [inline go/cmd/ct-fetch/ct-fetch.go:523]: oof

**Review by mozkeeler — APPROVED** [review]
Looks good to me.

File: go/cmd/ct-fetch/ct-fetch.go (hunk 1 above)
Comment (jschanck) [reply go/cmd/ct-fetch/ct-fetch.go:523]: That one was just cleanup, I was multiplying by time.Second in line 535. The bad one was `evaluationTime` in the health check. That one was causing the ct-fetch process to be rebooted every 7 minutes or so...
